[project]
name = "vipipe"
version = "0.1.0"
description = "Пайплайновая видео-обработка"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []


[tool.ruff.lint]
extend-ignore = ["E402"]

[tool.ruff]
line-length = 120
