services:
  decoder:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.ubuntu.gstreamer
    command: >
      gst-launch-1.0
        filesrc
            location=/app/media/demo30.mp4
        ! decodebin
        ! videoconvert
        ! videoscale
        ! videorate
        ! video/x-raw,format=RGB,width=1280,height=720,pixel-aspect-ratio=1/1,framerate=3000/1
        ! zmqsink
            address=ipc:///tmp/zmq_sockets/fpstest_decoder.ipc
            sync=true
    volumes:
      - zmq_sockets:/tmp/zmq_sockets

  fpstest:
    build: .
    command: >
      python3 main.py
        --reader_address ipc:///tmp/zmq_sockets/fpstest_decoder.ipc
    depends_on:
      - decoder
    volumes:
      - zmq_sockets:/tmp/zmq_sockets

  # renderer:
  #   build: .
  #   command: >
  #     python3 renderer.py
  #       --reader_address ipc:///tmp/zmq_sockets/metadetect_detector.ipc
  #       --writer_address ipc:///tmp/zmq_sockets/metadetect_renderer.ipc
  #   depends_on:
  #     - detector
  #   volumes:
  #     - zmq_sockets:/tmp/zmq_sockets

  # publisher:
  #   build:
  #     context: ../../
  #     dockerfile: docker/Dockerfile.ubuntu.gstreamer
  #   command: >
  #     gst-launch-1.0
  #       zmqsrc
  #           address=ipc:///tmp/zmq_sockets/metadetect_renderer.ipc
  #       ! videorate
  #       ! video/x-raw,framerate=4/1
  #       ! videoconvert
  #       ! x264enc
  #           speed-preset=ultrafast
  #           tune=zerolatency
  #       ! hlssink2
  #           playlist-root=http://localhost:8084/
  #           max-files=3
  #           playlist-length=2
  #           target-duration=2
  #           location=/app/metadetect/segment_%05d.ts
  #           playlist-location=/app/metadetect/playlist.m3u8
  #   depends_on:
  #     - renderer
  #   volumes:
  #     - zmq_sockets:/tmp/zmq_sockets
  #     - metadetect:/app/metadetect

  # sserver:
  #   build:
  #     context: ../../
  #     dockerfile: docker/Dockerfile.ubuntu.gstreamer
  #   command: >
  #     /bin/bash -c "cd /app/metadetect && python3 -u /app/src/scripts/sserver.py --port 8084"
  #   ports:
  #     - 8084:8084
  #   volumes:
  #     - metadetect:/app/metadetect

volumes:
  metadetect:
  zmq_sockets:
