services:
  decoder:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.ubuntu.gstreamer
    command: >
      gst-launch-1.0
        uridecodebin
            uri=rtsp://admin:admin@192.168.0.109:8554/live
        ! videoconvert
        ! videoscale
        ! video/x-raw,format=RGB,width=640,height=480,pixel-aspect-ratio=1/1
        ! zmqsink
            address=ipc:///tmp/zmq_sockets/facenet_test_raw.ipc
    depends_on:
      - facenet
      - publisher
    restart: always
    volumes:
      - zmq_sockets:/tmp/zmq_sockets
    network_mode: host

  facenet:
    build: .
    command: >
      python3 main.py
        --reader_address ipc:///tmp/zmq_sockets/facenet_test_raw.ipc
        --writer_address ipc:///tmp/zmq_sockets/facenet_test_processed.ipc
    volumes:
      - zmq_sockets:/tmp/zmq_sockets
      - facenet_test:/app/facenet_test

  publisher:
    build: 
      context: ../../
      dockerfile: docker/Dockerfile.ubuntu.gstreamer
    command: >
      gst-launch-1.0
        zmqsrc
            address=ipc:///tmp/zmq_sockets/facenet_test_raw.ipc
            read-timeout=60000
        ! videoconvert
        ! x264enc
        ! hlssink2
            playlist-root=http://localhost:8082/
            max-files=2
            playlist-length=2
            target-duration=2
            location=/app/facenet_test/segment_%05d.ts
            playlist-location=/app/facenet_test/playlist.m3u8
    volumes:
      - zmq_sockets:/tmp/zmq_sockets
      - facenet_test:/app/facenet_test

  sserver:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.ubuntu.gstreamer
    command: >
      /bin/bash -c "cd /app/facenet_test && python3 -u /app/src/scripts/sserver.py --port 8082"
    ports:
      - 8082:8082
    volumes:
      - facenet_test:/app/facenet_test

volumes:
  facenet_test:
  zmq_sockets:
