services:
  decoder:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.ubuntu.gstreamer
    command: >
      gst-launch-1.0
        filesrc
            location=/app/media/demo30.mp4
        ! decodebin
        ! videorate
        ! video/x-raw,framerate=1/1
        ! videoconvert
        ! video/x-raw,format=RGB
        ! zmqsink
            address=ipc:///tmp/zmq_sockets/cowdetector_raw.ipc
            send-timeout=5000
            sync=true
    volumes:
      - zmq_sockets:/tmp/zmq_sockets

  cowdetector:
    build: .
    command: >
      python3 main.py
        --reader_address ipc:///tmp/zmq_sockets/cowdetector_raw.ipc
        --writer_address ipc:///tmp/zmq_sockets/cowdetector_processed.ipc
    depends_on:
      - decoder
    volumes:
      - cowdetector:/app/cowdetector
      - zmq_sockets:/tmp/zmq_sockets

  publisher:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.ubuntu.gstreamer
    command: >
      gst-launch-1.0
        zmqsrc
            address=ipc:///tmp/zmq_sockets/cowdetector_processed.ipc
            read-timeout=60000
        ! videoconvert
        ! x265enc
            tune=zerolatency
            key-int-max=5
            speed-preset=ultrafast
        ! h265parse
        ! splitmuxsink
            muxer=mp4mux
            location=/app/cowdetector/segment_%05d.mp4
            max-size-time=5000000000
            send-keyframe-requests=true
    depends_on:
      - cowdetector
    volumes:
      - zmq_sockets:/tmp/zmq_sockets
      - cowdetector:/app/cowdetector

  sserver:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.ubuntu.gstreamer
    command: >
      /bin/bash -c "cd /app/cowdetector && python3 -u /app/src/scripts/sserver.py --port 8083"
    ports:
      - 8083:8083
    volumes:
      - cowdetector:/app/cowdetector

volumes:
  cowdetector:
  zmq_sockets:
